name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Read dotenv file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: ${{ github.workspace }}
      -
        name: Read version
        run: |
          echo "CLOJUPYTER_VERSION: ${{ env.CLOJUPYTER_VERSION }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/clojupyter:${{ env.CLOJUPYTER_VERSION }}
          build-args: |
            CLOJUPYTER_VERSION=${{ env.CLOJUPYTER_VERSION }}
